### ISSUE TITLE
Files and Folders designer does not evaluate WiX variables

### ISSUE THREAD

**Issue by leonard-thieu** [iswix-llc/iswix#3]
In my `InstallerMM` project, I have a project reference to the target project. We'll call it `MyProject`. I tried setting `SourceDir` to 

```xml
<?define SourceDir="$(var.MyProject.TargetDir)"?>
```

but this results in no files showing up. It looks like the designer is trying to evaluate it as a literal.

---

I can work around this by having 2 `SourceDir` declarations. The first one is assigned a hard coded path that IsWiX uses. WiX itself ignores the first declaration and uses the second one.

```xml
<?define SourceDir="..\MyProject\bin\Debug"?>
<?define SourceDir="$(var.MyProject.TargetDir)"?>
```

**Comment by iswix-llc** [comment]
A [tutorial](https://github.com/iswix-llc/iswix-tutorials/tree/master/desktop-application) is available to explain how to use IsWiX.  There is a section in there that talks about observing the contents of the deploy folder and then looking at the Sourcedir attribute pointing to the deploy folder teaching IsWiX where your files are.

In general IsWiX is designed to be used with the application code in one solution and the installer code in another solution.  This is for a variety of reasons such as new version of visual studio out that wix doesn't support yet, simplifying project / dependency / build order problems and encourage the creation of an installation model.

When you launch IsWiX it only knows the .wxs fragment that was sent to it.  It doesn't know the .wixproj or any other projects in the solution.  Thus we only support relative file path links as setup by the template and explained by the tutorial.

I hope that makes sense.   If someone thinks they could somehow solve the problem of knowing what var.MyProject.TargetDir resolves to  I'd be willing to consider it. Otherwise this design works well.

**Comment by iswix-llc** [comment]
BTW here is a nice video that parallels that tutorial.  You might find it useful.
[IsWiX Desktop Application Video](https://www.youtube.com/watch?v=nnV_OU6fk8c)

I'll leave this open for a few days for your feedback and then probably close this.

**Comment by leonard-thieu** [comment]
Ah, okay. I didn't realize it was intended. Thanks for the response.
