### ISSUE TITLE
Exclude EULA step from installation? 

### ISSUE THREAD

**Issue by hoc439** [iswix-llc/iswix#4]
Hi

I am using IsWiX project template to create MSI for my application.

In this, during installation, one EULA step appears. we would like to exclude this step. Could you please help me with this?

**Comment by hoc439** [comment]
I tried below code in with UI-CustomDialog.wxs file, but it didn't worked. It is showing EULA step. 

```
      <Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" Order="5">NOT Installed</Publish>
      <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="VerifyReadyDlg" Order="2"></Publish>
```
Is there easy way to disable the LicenseAgreement diallog?

**Comment by iswix-llc** [comment]
If you are using a Bootstrapper solution then you are creating an EXE that has it's own UI.  The MSI is installed silently and it's UI is never exposed so the change you tried wouldn't do anything.    IsWiX really only creates the starting template for a bootstrapper and nothing beyond that.  This is a WiX question and a google search finds:

https://stackoverflow.com/questions/16978501/how-to-create-a-bootstrapper-application-without-a-license-agreement-step

**Comment by hoc439** [comment]
Is there a way to handle this in MSI setup project?

We are not using EXE project as MSI is installed silently and user will not be able to see UI (installation option, location etc)

**Comment by iswix-llc** [comment]
Your last comment seems to conflict with your issue.  The issue is to suppress the EULA but the last comment says the MSI is installed silently and use will not be able to see UI.  I don't understand.

**Comment by hoc439** [comment]
Sorry for confusion. To clarify again-
I am trying to run MSI separately from WixSetup project. In this case, I want avoid EULA step.

If I use bootstrapper project (.exe) then EXE has different screens (which we don't want). When we run EXE then MSI installed behind the scene (I mean silently).

Hope this helps to clarify any confusion.

**Comment by hoc439** [comment]
I have found another option - https://stackoverflow.com/questions/597025/how-to-build-a-minimal-wix-installer-ui-without-a-license-page
But not able to incorporate in your template. Can you please help me here?

**Comment by hoc439** [comment]
Solved using this link - https://stackoverflow.com/questions/38145181/removing-eula-from-wixui-featuretree

**Comment by iswix-llc** [comment]
Copying the entire wixui source into your project is a good way to go if you want full control over customizing the WiX UI.   The downside is  you won't automatically get improvements when you switch to new versions of WiX.  This is why IsWiX doesn't do this by default in it's project template.  It doesn't prevent you from doing it either.

You might want to create a "vendor" branch in your source control system to keep those files.  Then you can create a branch where you make your changes.   Then when a new versino of WiX comes out you can grab the latest wxs files and check them into your vendor branch and merge them into your changed branch.  

Otherwise the simple ControlEvent/Publish override elements should work just fine. I  do it all the time.

**Comment by iswix-llc** [comment]
PS- You should remove the bootstrapper project from the solution if you don't want it to speed up your builds.   IsWiX also has an "IsWiX solution" template that doesn't include a bootstrapper project if you want to create more solutions in the future that only create an MSI.
