### ISSUE TITLE
Is this product still relevant and supported?

### ISSUE THREAD

**Issue by bgoldca** [iswix-llc/iswix#5]
Hi. I just downloaded the .zip of the repo and I have no idea what to do with it. I tried opening installer.sln but I get all kinds of errors so then I tried Application.sln and that won't compile either. (I'm using VS 2017). The latest error is : Missing Compiler required member 'Microsoft.CSharp.RunTimeBinder.Binder.Convert' Are there notes somewhere on how we're supposed to build/use this software?

**Comment by iswix-llc** [comment]
ISWIX is currently compiled using VS2015. It has a CI/CD pipeline and is one of the simplest projects to build that I know of.  It has very few dependencies and all of them are included in the repos.  I don't know what your compiler problems are but it sounds like something has gone wrong in your migration to VS2017.  A quick google search suggests you are missing a reference to Microsoft.CSharp.dll.

**Comment by iswix-llc** [comment]
BTW you might want to look at the ISWIX Tutorials repos for an overview of what ISWIX is and how to use it before you start trying to build it.  I find it relevant.  If you decide you want to work on it and submit pull requests I can give you an orientation to the design.  It was developed by a couple people over a few months initially and some of it I'd like to refactor but otherwise it works really well.
