### ISSUE TITLE
After installation of 4.12.1.0, creating a new iswix solution (either version) errors out with VS 2017 15.8.4/15.8.5

### ISSUE THREAD

**Issue by frizzr** [iswix-llc/iswix#9]
The error is below. It creates the folders for the solution but no files are created underneath them:

![image](https://user-images.githubusercontent.com/829843/45843814-6eeecd80-bcd5-11e8-8b54-4789f5a31c1b.png)

This issue is not there with the previous version 4.11.18042.1...just FYI.

It sounds like a missing dependency. You did remove this dependency here, but you may still need it: https://github.com/iswix-llc/iswix/commit/67b3037fcbdd7f03b54818c8771e9b49722a2690#diff-a0b02469e831dbdafed297e01e323e03

I also use Resharper and VsVim within Visual Studio. If you can't reproduce, I can provide all my plugins.

**Comment by Helmi-helmutson** [comment]
+1 same error here

**Comment by rexunderlinehxiao** [comment]
+1 same error here

**Comment by JojoJgeorge** [comment]
+1 And here

**Comment by chrpai** [comment]
I apologize as I never noticed an alert for this issue. I  assume you've gone back to a previous version of IsWiX and are operational.   I will look at this issue this weekend.  Will you be available to test a fix?  Do you know what the missing dependency is?  I haven't begun my root cause investigation yet.

**Comment by chrpai** [comment]
Release 4.12.2.0 published.  Please retest and confirm issue resolution.
